filename: rust-lib
extension: yaml
source_full_path: ./.github/workflows
destination_full_path: ./out/DGY7oL0c
source_local_path: .github/workflows
destination_local_path: DGY7oL0c
hash: f7d6410bcebd86a9
group_id: DGY7oL0c
